- models.py
- templates/base.html
- templates/mesto.html
- views.py
Fix - loading data for `/misto/<misto>` and `/mesto/<mesto>` from database.
Restyling a bit - can be customized or rejected.
> Restyle a bit and make working obtaining of data from database.

- data/db_create.sql
- freespace_fetcher.py
- models.py
- templates/ockovani_info.html
- views.py
Import_log is working
Aggregation rewritten
Last update fixed
> Fixed minor issues, rewritten the aggregation

- app.py
- config.py
- freespace_fetcher.py
- models.py
- static/css/styles.css
- templates/base.html
- templates/index.html
- templates/mesto.html
- templates/misto.html
- templates/ockovani_info.html
- views.py
resolves parts of #5 and #25 
Proposals:
> UI improvements 2

- app/__init__.py
- app/templates/kraj.html
- app/templates/misto.html
- app/templates/okres.html
- app/views.py
closes #76 
"dnes", "včera" is not possible because of static page
> Date format - added weekday

- app/__init__.py
- app/filters.py
- app/templates/misto.html
- app/templates/statistiky.html
- app/views.py
Improved statistic and misto page
> Feature statsnew

- app/__init__.py
- app/filters.py
- app/templates/base.html
It should be removed also from the create_static_pages.sh - this was done in another PR - #106
> Url subdirectory removed

- .github/workflows/update-web.yml
Please merge it also to the main
> Fix for update web pipeline

- .github/workflows/update-web.yml
> fixed condition for update-web pipeline

- app/static/styles/style.css
- app/templates/base.html
- app/templates/misto.html
- app/templates/statistiky.html
Far from ideal/nice but better than nothing
- overflows in column "kategorie" hidden using ellipsis
- bootstrap tooltips - closes #118
> better tooltips, table overflow hidden using ellipsis

- scripts/create_static_pages.sh
> style.css wget fixed

- app/templates/base.html
- app/templates/index.html
- app/templates/kraj.html
- app/templates/macros.html
- app/templates/mista.html
- app/templates/misto.html
- app/templates/okres.html
- app/views.py
- tables at pages kraj, okres are now aggregated => ready for new metrics
- column "volna mista" has info icon for more info
- tables as reusable macro
Tooltip messages should be probably reformulated.
> Tables with vaccionation center overviews aggregated

- app/templates/macros.html
- app/views.py
Last 7 days vaccinated, people with vacc. date added
> Feature reservation

- app/opendata_fetcher.py
delete old delivery in the same transaction as inserts
> fetcher - fixed possible bug

- app/static/styles/style.css
- app/templates/base.html
- app/templates/statistiky.html
- app/views.py
* added totals
* some column names changed
* table of vaccinated people changed
* UI improvements
closes #86 #117
> Stats page improved + minor changes

- dockerize/entrypoint.sh
I don't know if it is correct, but without compute-metrics is not working mista and another pages.
I use application in docker env.
> Update entrypoint.sh / compute-metrics

- app/static/styles/style.css
- app/templates/base.html
- app/templates/codelat.html
- app/templates/misto.html
- app/views.py
I'm opening discussion here, how we should approach this topic.
Close #208
> #208 - what to do

- app/templates/kraj.html
- app/templates/macros.html
- app/templates/statistiky.html
- app/views.py
Universal table for vaccination / age
> 223 - first approach

- app/queries.py
- app/templates/base.html
- app/templates/kraj.html
- app/templates/macros.html
- app/templates/mapa.html
- app/templates/misto.html
- app/views.py
- map fixed
- map detail improved
- buttons hiddent for disabled centers
- description of deltas added
merge after #260
> Improvements, bugfixes

- README.md
- scripts/create_static_pages.sh
> Fail pipeline if wget fails

- .github/workflows/update-data.yml
Do not merge it now, we will wait for UZIS if data will be still ready around 8 a.m.
> Update for CEST

- app/etl/center_metrics_etl.py
- app/queries.py
- app/templates/macros/graphs/fronta.html
- app/templates/macros/graphs/ockovani.html
- app/templates/macros/graphs/registrace.html
- app/templates/misto.html
- app/views.py
> Graph for reservations, vaccination and usage comparison

- app/queries.py
- app/templates/macros/graphs/fronta.html
- app/templates/macros/graphs/registrace.html
- app/templates/macros/tables/stav_registraci.html
> Categories without any reservation in last 2 weeks highlighted

- app/static/css/style.css
- app/static/js/main.js
- app/templates/macros/tables/prehled_mist.html
- app/templates/macros/tables/stav_registraci.html
> Sortable tables

- app/queries.py
- app/templates/macros/graphs/nakazeni.html
- app/templates/macros/graphs/umrti.html
- app/templates/statistiky.html
- app/views.py
> Graphs of new cases and deaths per week

- app/etl/center_metrics_etl.py
- app/etl/cr_metrics_etl.py
- app/etl/kraj_metrics_etl.py
- app/queries.py
- app/views.py
> Queries for one dose vaccines

- app/static/js/main.js
- app/templates/base.html
- app/templates/statistiky.html
> Hotjar, fixes

- app/queries.py
- app/static/css/style.css
- app/templates/macros/tables/prehled_mist.html
> Barrier-free filtering

- app/templates/odkazy.html
- app/views.py
Low priority - links to datasource and covid test added
> New links and fixed dataquality report about vaccination

- app/etl/center_metrics_etl.py
- app/etl/cr_metrics_etl.py
- app/etl/kraj_metrics_etl.py
- app/etl/okres_metrics_etl.py
- app/fetcher/registrations_fetcher.py
- app/queries.py
This is a proposal how we should handle the new indicator ockovani to have better and correct results.
> Fixing conditions for registrace

- app/queries.py
- app/templates/macros/tables/stav_ockovani.html
- app/templates/macros/tables/stav_registraci.html
- app/templates/macros/tables/stav_registraci_kategorie.html
> Count of people with reservation in tables

- app/queries.py
- app/templates/index.html
Fixing filter + adding hidden link
> DataQuality first draft + fixing filter

- app/fetcher/centers_fetcher.py
- app/fetcher/distributed_fetcher.py
- app/fetcher/used_fetcher.py
> Missing centers during fetch fixed

- app/queries.py
- app/templates/macros/tables/volna_mista.html
- app/templates/misto.html
- app/views.py
> Free slots

- app/queries.py
- app/templates/macros/tables/nejvykonnejsi_mista.html
- app/templates/macros/tables/prehled_ockovani_tyden.html
- app/templates/statistiky.html
- app/views.py
> Top centers and days replaced

- .github/workflows/update-data.yml
I've added it to crontab, token has to be filled and line uncommented. Token needs `repo` and `workflow` permissions.
```
00 8 * * * curl -X POST 'https://api.github.com/repos/msusicky/ockovani-covid/actions/workflows/6451095/dispatches' -H 'Authorization: token <MY TOKEN>' -H 'Accept: application/vnd.github.v3+json' -d '{ "ref": "master" }'
```
> Cron trigger

- app/templates/macros/tables/prehled_mist.html
> #455 - Selfpaid places filtering

- app/queries.py
- app/templates/macros/graphs/fronta.html
- app/templates/macros/graphs/registrace.html
- app/templates/praktici.html
- app/templates/statistiky.html
- app/views.py
> Tab order changed

- app/models.py
- app/queries.py
- app/templates/macros/tables/prehled_mist.html
- app/templates/misto.html
> Data form CFA used in detail and for filtering

- app/fetcher/centers_detail_fetcher.py
closes #551 
It has to be tested properly as all data will be available
> Add missing centers from CFA

- app/templates/macros/graphs/nakazeni.html
- app/templates/macros/graphs/umrti.html
Dirty solution, but if we want it only for these two graphs...
> Auto rescale Y

- app/fetcher/reservations_api_fetcher.py
- requirements.txt
Reverts msusicky/ockovani-covid#568
> Revert "2.5.14"

- app/templates/index.html
@msusicky feel free to edit it
> News update

- app/queries.py
- app/templates/macros/tables/volna_mista.html
> Third doses in capacities overview table

- app/templates/base.html
- app/templates/praktici.html
> Zachrante vakciny removed

- app/queries.py
- app/templates/macros/tables/stav_ockovani.html
- app/templates/macros/tables/stav_ockovani_indikace.html
- app/templates/statistiky.html
We should fix age categories before merging it
> Third doses in vaccinated table, code simplified

- app/templates/macros/graphs/nakazeni.html
- app/templates/macros/graphs/umrti.html
> Deaths and infected charts - absolute counts

- app/filters.py
- app/templates/macros/graphs/nakazeni.html
- app/templates/macros/graphs/umrti.html
- app/templates/statistiky.html
> Comparison chart - week in header

- app/fetcher/centers_api_fetcher.py
- app/fetcher/fetcher.py
- app/fetcher/fetcher_launcher.py
- app/fetcher/hospital_analysis_fetcher.py
- app/fetcher/opening_hours_fetcher.py
- app/fetcher/registrations_fetcher.py
- app/fetcher/reservations_api_fetcher.py
- app/fetcher/reservations_fetcher.py
- app/fetcher/supplies_fetcher.py
> Fetchers redesign

- .github/workflows/post-tweet.yml
- .github/workflows/update-data-hourly.yml
- README.md
- app/fetcher/fetcher_launcher.py
- app/templates/base.html
- app/templates/macros/tables/volna_mista.html
- app/verifier.py
> Hourly update fixes

- app/templates/index.html
closes #673 
check date before deployment!
> Hourly updates - news

- app/queries.py
> SQL alchemy warnings fixed

- app/queries.py
- app/templates/macros/graphs/nakazeni.html
- app/templates/macros/graphs/testy.html
- app/templates/macros/graphs/umrti.html
- app/templates/statistiky.html
- app/views.py
> Tests positivity chart

- app/templates/base.html
- app/templates/index.html
- app/templates/macros/graphs/prijate_davky.html
- app/templates/napoveda.html
> Update message simplified, help updated

- .github/workflows/clean-db.yml
- .github/workflows/db-cleanup.yml
- app/commands.py
> #711 DB cleanup implemented

- app/templates/mista.html
- app/templates/mista_mapa.html
- app/templates/nabidky.html
- app/templates/nabidky_mapa.html
- app/templates/praktici.html
- app/templates/praktici_mapa.html
- app/templates/praktik.html
- headlines unified
- map button improved on mobiles
- max zoom limit for gp maps
> Improvements

- app/twitter_bot.py
> Tweet updated

- app/commands.py
vacuum return only None, there is no need to check result - it should throw an exception in case of failure
> Clean db exit code fixed

- app/templates/macros/graphs/nakazeni.html
- app/templates/macros/tables/pravdepodobnost_hospitalizace.html
> Warnings about missing reinfections

- migrations/versions/e1bc70696bb8_.py
přidáno do staré migrace - chceme ji spouštět jen pro nové instalace
> Chybějící vakcíny

- app/templates/nabidky.html
- app/templates/praktici_admin.html
> Zruseni nabidky praktiku
